name = "tena-travel-expeditions"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# Configuración de base de datos Cloudflare D1 en red
[[d1_databases]]
binding = "DB"
database_name = "tena-travel-d1-prod"
database_id = "tena-travel-d1-prod"
